municipality_id: shizuoka
name: 静岡市
base_url: https://www.city.shizuoka.lg.jp
index_urls:
  # 事業者向け情報
  - https://www.city.shizuoka.lg.jp/p000345.html
  # しごと・産業
  - https://www.city.shizuoka.lg.jp/p009299.html

rate_limit_seconds: 2.0
