municipality_id: hamamatsu
name: 浜松市
base_url: https://www.city.hamamatsu.shizuoka.jp
index_urls:
  # 産業振興
  - https://www.city.hamamatsu.shizuoka.jp/sangyo/shinko/index.html
  # 創業・スタートアップ支援
  - https://www.city.hamamatsu.shizuoka.jp/sangyo/startup/index.html
  # エネルギー・環境支援
  - https://www.city.hamamatsu.shizuoka.jp/sangyo/energy/index.html

rate_limit_seconds: 2.0
